services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-DK_BLOG}
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - docker-base_default

networks:
  docker-base_default:
    external: true
